spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ft?serverTimezone=UTC
      username: root
      password: .Lihaolong007
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.ft.server.entity
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  pageSizeZero: false
im:
  appkey: 1156210717083467#demo
  client-id: YXA6LBdhWMMlTAWn4auHpgdOfA
  client-secret: YXA6yiQ6YU8MO80pkojMx1bFf6NINCk
