spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC
      username: root
      password: .Lihaolong007
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.ft.server.entity